import Layout from '@/Layout/Layout'
import { NextIntlClientProvider } from 'next-intl'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
	Weight: ['400', '700', '800', '900'],
})

export const metadata = {
	title: 'Isab Security',
	description: 'Generated by create next app',
	icons: {
		icon: '/tt.svg',
	},
}

export default async function RootLayout({ children, params }) {
	const { locale } = await params

	return (
		<html lang={locale}>
			<body className={`${inter.className} antialiased gradients`}>
				<NextIntlClientProvider>
					<Layout>{children}</Layout>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
